name: Run pytest and pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Install and run pylint
        run: |
          pip install pylint
          pylint --fail-under=${{ vars.PYLINT_THRESHOLD }} app/

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          
          # Generate a tag based on branch name
          tag_name="${branch_name}-latest"
          
          # Build and tag the Docker image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/edgematrix:$tag_name .

          # Push the Docker image to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edgematrix:$tag_name