name: Run pytest and pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pylint


      - name: Run tests
        run: pytest

      - name: Install and run pylint
        run: |
          pip install -r requirements.txt
          pylint --fail-under=8 app/